name: PHP Skills

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ConnectRabbitMQ:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock to ConnectRabbitMQ
      run: composer validate --strict
      working-directory: ./PHP/ConnectRabbitMQ

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies to ConnectRabbitMQ
      run: composer install --prefer-dist --no-progress
      working-directory: ./PHP/ConnectRabbitMQ

    - name: Run test suite to ConnectRabbitMQ
      run: composer test
      working-directory: ./PHP/ConnectRabbitMQ

    - name: Run PHPStan to ConnectRabbitMQ
      run: composer phpstan
      working-directory: ./PHP/ConnectRabbitMQ
